### ISSUE TITLE
Marstek Venus C with BMS V151 suddenly shows unreasonable energy statistics

### ISSUE THREAD

**Issue by BorisProhaska** [Superduper1969/MarstekVenus-LilygoRS485#5]
I've updated my VENUS C BMS FW to 1.5.1, and suddenly all the energy statistics show unreasonable values (in the Marstek App it's fine though).

Marstek Daily Charging Energy	        1193.30 kWh
Marstek Monthly Charging Energy	2397.10 kWh
Marstek Total Charging Energy	        2457.34 kWh

Discharging however, still shows correct values:

Marstek Daily Discharging Energy	0.10 kWh
Marstek Monthly Discharging Energy	8.42 kWh
Marstek Total Discharging Energy	56.55 kWh

Could you please check? Thank you

**Comment by BorisProhaska** [comment]
No, i never figured it out. As it happens sporadically, i edit the total charged energy in the statistics page - just to have valid data in the long run.

**Comment by Superduper1969** [comment]
There are 2 ways to get this information:
- The older versions of firmware do NOT provide correct Daily/monthly data, this is why they are calculated in "marstek_venus_battery_control.yaml"
- The later versions (V14x+) do seem to provide the correct data but if this is not the case stick to the calculated method.

**Comment by kloppy** [comment]
Here is my attempt at a workaround. This should give a new sensor which detects the sudden increases in energy and subtracts them.

**Trigger based template sensor** (in configuration.yaml)

```yaml
template:
  - trigger:
    - platform: event
      event_type: set_sensor
    condition: "{{ (trigger.event.data.target == 'marstek_1_total_charged_energy_corrected') | bool(false) }}"
    sensor:
      - unique_id: 4444dbfb-edd2-4b51-adb1-817c6465efdb
        name: marstek_1_total_charged_energy_corrected
        state_class: total
        unit_of_measurement: kWh
        device_class: energy
        state: "{{ trigger.event.data.value }}"
        availability: "{{ is_number(trigger.event.data.value) }}"
        attributes:
          factor: "{{ trigger.event.data.factor }}"
```

**Automation** that updates the sensor

```yaml
alias: update the corrected marstek energy sensor
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.marstek_1_total_charged_energy
    to: null
conditions: []
actions:
  - alias: calculate the new sensor state
    variables:
      result: >
        {% set previous = states('sensor.marstek_1_total_charged_energy_corrected') | float(-1) -%}
        {% set factor = state_attr('sensor.marstek_1_total_charged_energy_corrected', 'factor') | float(-1) -%}
        {% set charged = states('sensor.marstek_1_total_charged_energy') | float(-1) -%}
        {% set discharged = states('sensor.marstek_1_total_discharged_energy') | float(-1) -%}
        {% set step = 1193.06 -%}
        {# are we missing the previous value? -#}
        {% if previous < 0 and charged > 0-%}
        {% set previous = charged -%}
        {% endif -%}
        {# are we missing the factor? -#}
        {% if factor < 0 and charged > 0 and discharged > 0 -%}
        {% set factor = ((charged - 1.5 * discharged) / step) | round | int -%}
        {% endif -%}
        {# did another step appear? -#}
        {% if charged > 0 and previous > 0 and factor > 0 and (charged - factor * step) - previous > 0.999 * step -%}
        {% set factor = factor + (((charged - factor * step) - previous) / step) | round | int -%}
        {% endif -%}
        {# return the new corrected value -#}
        {{ {
        'ok': charged > 0 and factor > 0,
        'value': (charged - factor * step) | round(2),
        'factor': factor
        } -}}
  - if:
      - condition: template
        value_template: "{{ result.ok }}"
        alias: if the calculated result is valid
    then:
      - alias: set the new sensor state
        event: set_sensor
        event_data:
          target: marstek_1_total_charged_energy_corrected
          value: "{{ result.value }}"
          factor: "{{ result.factor }}"
mode: single

```
